apiVersion: apps/v1
kind: Deployment
metadata:
  name: impact-fluentd
  labels:
    app: impact
spec:
  replicas: 1
  selector:
    matchLabels:
      env: development
      name: impact-fluentd
  template:
    metadata:
      name: impact-fluentd
      labels:
        env: development
        name: impact-fluentd

      namespace: impact
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.13.0-debian-1.0
          volumeMounts:
            - mountPath: /fluentd/etc
              name: fluentd-conf
          ports:
            - containerPort: 24224
      volumes:
        - name: fluentd-conf
          configMap:
            defaultMode: 420
            name: fluentd-conf
            items:
              - key: fluentd-conf
                path: fluent.conf
