apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
  namespace: impact
data:
  fluentd-conf: "# Receive events from 24224/tcp \n
 # This is used by log forwarding and the fluent-cat command \n
 <source>\n
   @type forward\n
   port 24224\n
 </source>\n

 ## match and dump to console\n
 <match>\n
   @type stdout\n
   @id output_stdout\n
 </match>"