apiVersion: v1
kind: Service
metadata:
  name: impact-fluentd
  namespace: impact
spec:
  type: NodePort
  selector:
    env: development
    name: impact-fluentd
  ports:
    - name: fluentd
      port: 24224
      nodePort: 31000
      targetPort: 24224


