apiVersion: v1
kind: Service
metadata:
  name: impact-fluentd
spec:
  type: ClusterIP
  selector:
    env: development
    name: impact-fluentd
  ports:
    - name: fluentd
      port: 31000
      targetPort: 24224


